name: Salesforce Deployment Test-Org

on:
  push:
    paths:
      - 'force-app/**'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate with JWT
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} \
                              --jwtkeyfile server.key \
                              --username ${{ secrets.SF_USERNAME }} \
                              --instanceurl ${{ secrets.SF_INSTANCE_URL }}

      - name: Push source to org
        run: |
          sfdx sfdx force:source:deploy --targetusername "${{ secrets.SF_USERNAME }}" --loglevel DEBUG
